improved personality
resin-io-modules/hubot-open-url pull request #17
Opened 2017-02-16 12:55 UTC by sqweelygig

closes #13
* adds personality to the poke-url script

2017-02-16 15:02 UTC, lurch commented
Looks like this PR does _more_ than just improve the personality - it seems to include tweaks to the URL-opening stuff too. Was that intentional?

2017-02-16 19:37 UTC, pimterry submitted a review, later dismissed
Two minor points we could tweak, but otherwise LGTM (@lurch's comments notwithstanding ofc)

2017-02-16 19:37 UTC, pimterry commented on src/open-url.coffee
> +			throw new PersonalityError("Text not found for #{purpose}")
I think it's reasonable for getText to return `null` or `undefined` if no text exists, and that'd let you drop `PersonalityError` and make `buildMessage` simpler, since it can just check for null.

2017-02-16 19:37 UTC, pimterry commented on src/open-url.coffee
> +class Personality
Agree this class doesn't need to be it's own module now, but you could put it in a separate file to keep things clearer here.

2017-02-17 11:18 UTC, pimterry commented on src/open-url.coffee
> +			createErrorReporter(context)(error)
This reverts the `Promise.try` improvement, which was a fix from a previous review. Why?

2017-02-17 11:31 UTC, CameronDiver requested changes

2017-02-17 11:31 UTC, CameronDiver commented on src/personality.coffee
> +				deny: ["Sod off, I'm not doing that"]
Can we get consistent quotes on these strings please? The standard says single quotes `'` for non interpolation strings, but at the very least these should all be the same.

2017-02-17 11:31 UTC, CameronDiver commented on src/open-url.coffee
> +			createErrorReporter(context)(error)
I agree with Tim here, you should use a single `catch` with `Promise.try`

2017-02-17 11:46 UTC, sqweelygig commented on src/open-url.coffee
> +			createErrorReporter(context)(error)
Discussed bluebird in pm, implementing

2017-02-17 11:57 UTC, CameronDiver approved these changes
LGTM

2017-02-17 11:57 UTC, CameronDiver commented on src/open-url.coffee
> +Promise = require 'bluebird'
It's completely preference but I find it's more obvious if the external dependencies (in this case `bluebird`) are imported before the local dependencies, and this is a standard that others do follow, but it's not a hard and fast rule.

2017-02-17 12:01 UTC, merged